apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azuredisk-csi
  
